'use strict';
let products=[];let activeFilter='All';let searchQuery='';let restockQuantity=50;const stockAdjustments={};
const esc=s=>String(s).replace(/[&<>"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]));
const status=(s,t)=>s===0?'Out of Stock':s<=t?'Low Stock':'In Stock';
const sClass=s=>s==='In Stock'?'in-stock':s==='Low Stock'?'low-stock':'out-stock'; const bClass=s=>s==='In Stock'?'status-in-stock':s==='Low Stock'?'status-low-stock':'status-out-stock';
async function load(){const r=await window.auth.apiFetch('/api/products');const j=await r.json();products=(j.data||[]).map(p=>({...p,category:p.category?.name||''}));render();}
async function adjust(id,adj){if(!adj) return;await window.auth.apiFetch('/api/stock/adjust',{method:'POST',body:JSON.stringify({productId:id,type:adj>0?'IN':'OUT',quantity:Math.abs(adj),note:'stock page adjustment'})});await load();}
function filtered(){return products.filter(p=>{const st=status(p.stock,p.reorderThreshold);return (!searchQuery||p.name.toLowerCase().includes(searchQuery)||p.sku.toLowerCase().includes(searchQuery))&&(activeFilter==='All'||st===activeFilter);});}
function render(){const tbody=document.getElementById('stock-table-body');const rows=filtered();tbody.innerHTML=rows.length?rows.map(p=>`<tr data-product-id="${p.id}" data-current-stock="${p.stock}" data-reorder-threshold="${p.reorderThreshold}" data-status="${status(p.stock,p.reorderThreshold)}"><td class="td-checkbox"><input type="checkbox"></td><td class="td-product-name">${esc(p.name)}</td><td>${esc(p.sku)}</td><td>${esc(p.category)}</td><td><span class="td-stock-value ${sClass(status(p.stock,p.reorderThreshold))}">${p.stock} <span class="td-stock-units">units</span></span></td><td>${p.reorderThreshold}</td><td><span class="status-badge ${bClass(status(p.stock,p.reorderThreshold))}"><span class="status-dot"></span>${status(p.stock,p.reorderThreshold)}</span></td><td><div class="stock-adjust-controls"><button class="adjust-btn adjust-minus">-</button><input type="number" class="adjust-input" value="${stockAdjustments[p.id]||0}"><button class="adjust-btn adjust-plus">+</button><button class="apply-btn" style="display:${stockAdjustments[p.id]?'block':'none'}">Apply</button></div></td></tr>`).join(''):'<tr><td colspan="8">No products match your filter.</td></tr>';document.getElementById('footer-text').textContent=`Showing ${rows.length} of ${products.length} products`;}
document.addEventListener('DOMContentLoaded',async()=>{document.getElementById('search-input').addEventListener('input',e=>{searchQuery=e.target.value.toLowerCase().trim();render();});document.querySelectorAll('.tab-filter-btn').forEach(b=>b.addEventListener('click',()=>{activeFilter=b.dataset.filter;document.querySelectorAll('.tab-filter-btn').forEach(x=>x.classList.remove('active'));b.classList.add('active');render();}));document.getElementById('restock-qty').addEventListener('input',e=>restockQuantity=Math.max(1,parseInt(e.target.value||'1',10)));document.getElementById('stock-table-body').addEventListener('click',async e=>{const row=e.target.closest('tr');if(!row)return;const id=+row.dataset.productId;if(e.target.closest('.adjust-minus')||e.target.closest('.adjust-plus')){stockAdjustments[id]=(stockAdjustments[id]||0)+(e.target.closest('.adjust-plus')?1:-1);render();}if(e.target.closest('.apply-btn')){await adjust(id,stockAdjustments[id]||0);delete stockAdjustments[id];}});document.getElementById('bulk-restock-btn').addEventListener('click',async()=>{const ids=[...document.querySelectorAll('.stock-table tbody input[type="checkbox"]:checked')].map(cb=>+cb.closest('tr').dataset.productId);if(ids.length){for(const id of ids) await adjust(id,restockQuantity);} else {for(const p of products.filter(p=>p.stock<=p.reorderThreshold)) await adjust(p.id,restockQuantity);}await load();});await load();});
