'use strict';
let usersData=[]; const mapRole={ADMIN:'Administrator',MANAGER:'Manager',STAFF:'Viewer'};
const revRole={Administrator:'ADMIN',Manager:'MANAGER',Viewer:'STAFF'};
const revStatus={Active:'ACTIVE',Inactive:'INACTIVE'};
function initials(n){return n.split(/\s+/).map(x=>x[0]).join('').slice(0,2).toUpperCase();}
async function loadUsers(){const r=await window.auth.apiFetch('/api/users');const j=await r.json();usersData=(j.data||[]).map(u=>({id:u.id,name:u.name,email:u.email,role:mapRole[u.role]||u.role,status:u.status==='ACTIVE'?'Active':'Inactive',lastActive:new Date(u.createdAt).toLocaleDateString(),initials:initials(u.name)}));renderTable();}
function renderTable(){const t=document.getElementById('usersTableBody');t.innerHTML=usersData.map(u=>`<tr data-user-id="${u.id}"><td>${u.name}</td><td class="td-email">${u.email}</td><td>${u.role}</td><td>${u.status}</td><td>${u.lastActive}</td><td><button class='btn-edit'>Edit</button><button class='btn-toggle'>${u.status==='Active'?'Deactivate':'Activate'}</button></td></tr>`).join('');}
// keep existing modal wiring but persist through API
const modal=document.getElementById('userModal'),inputName=document.getElementById('inputName'),inputEmail=document.getElementById('inputEmail');
function getActiveToggleValue(id){const a=document.querySelector(`#${id} .toggle-btn.active`);return a?a.dataset.value:null;}
function setGroup(id,val){document.querySelectorAll(`#${id} .toggle-btn`).forEach(b=>b.classList.toggle('active',b.dataset.value===val));}
function openModal(mode,u){modal.dataset.mode=mode;if(u){modal.dataset.userId=u.id;inputName.value=u.name;inputEmail.value=u.email;setGroup('roleToggleGroup',u.role);setGroup('statusToggleGroup',u.status);} else {delete modal.dataset.userId;inputName.value='';inputEmail.value='';setGroup('roleToggleGroup','Viewer');setGroup('statusToggleGroup','Active');} modal.style.display='flex';}
function closeModal(){modal.style.display='none';}
async function persistModal(){const payload={name:inputName.value.trim(),email:inputEmail.value.trim(),role:revRole[getActiveToggleValue('roleToggleGroup')],status:revStatus[getActiveToggleValue('statusToggleGroup')]};if(modal.dataset.mode==='add'){await window.auth.apiFetch('/api/users',{method:'POST',body:JSON.stringify({...payload,password:'ChangeMe123!'})});}else{await window.auth.apiFetch(`/api/users/${modal.dataset.userId}`,{method:'PUT',body:JSON.stringify(payload)});}closeModal();await loadUsers();}
document.addEventListener('DOMContentLoaded',()=>{document.getElementById('addUserBtn').onclick=()=>openModal('add');document.getElementById('modalSaveBtn').onclick=persistModal;document.getElementById('modalCloseBtn').onclick=closeModal;document.getElementById('modalCancelBtn').onclick=closeModal;document.getElementById('usersTableBody').addEventListener('click',async e=>{const tr=e.target.closest('tr');if(!tr)return;const u=usersData.find(x=>x.id===+tr.dataset.userId);if(e.target.closest('.btn-edit')) openModal('edit',u);if(e.target.closest('.btn-toggle')){await window.auth.apiFetch(`/api/users/${u.id}`,{method:'PUT',body:JSON.stringify({status:u.status==='Active'?'INACTIVE':'ACTIVE'})});await loadUsers();}});loadUsers();});
